### ISSUE TITLE
i cant run

### ISSUE THREAD

**Issue by The-Erf** [valentinfrlch/ha-gpt4vision#1]
Hello, I added the code to the yaml file like in the document, but after restarting ha, I still have an error in the yaml file :)

![1](https://github.com/valentinfrlch/ha-gpt4vision/assets/82929677/2fec8794-bbf8-4edf-acbf-411665c6e464)

![2](https://github.com/valentinfrlch/ha-gpt4vision/assets/82929677/29a94148-99da-4724-b431-40469c658c97)

**Comment by valentinfrlch** [comment]
You don’t need to add it from the UI. After adding it to the configuration.yaml and restarting, you should already have the service. To try it out go to the developer tools tab (or in any automation or script) search for the service `gpt4vision.image_analyzer`. 

If it still doesn’t work, feel free to reopen this issue :)
