### ISSUE TITLE
getting a validation error 400

### ISSUE THREAD

**Issue by hsman2** [valentinfrlch/ha-gpt4vision#24]
Keep getting this when selecting a camera entity, works find with the sub view or image entity but the full stream camera entity gives this error when running the script. 
![Screenshot_20240624-084832](https://github.com/valentinfrlch/ha-gpt4vision/assets/92912889/f0e9c2cd-0df7-472d-9d71-18e9c8c70f02)

**Comment by valentinfrlch** [comment]
Please enable debugging, reproduce the error and attach the relevant logs

To enable debugging, add the following to your configuration.yaml:
```
logger:
  logs:
    custom_components.gpt4vision: debug
```

**Comment by valentinfrlch** [comment]
There should be a `Ollama request data:` entry. That is only logged if you enable the debugger that I asked you to enable however.

**Comment by hsman2** [comment]
`[2024-06-24` 12:56:24.762 DEBUG (MainThread) [custom_components.gpt4vision.request_handlers] Ollama request data: {'model': 'llava:13b', 'messages': [{'role': 'user', 'content': 'Image 1:', 'images': 

['Probably 20 pages of just random text and number']},

{'role': 'user', 'content': "This image is the front door video camera. tell me if there's anything suspicious going on or people acting suspicious. keep your response less the 2 sentences. only tell me if there's anything suspicious. If you do see people tell me and tell me how many people you see. if nothing looks suspicious and there are no people in the image just say everything looks good."}], 'stream': False, 'options': {'max_tokens': 100, 'temperature': 0.6}}
2024-06-24 12:56:28.882 ERROR (MainThread) [custom_components.gpt4vision.request_handlers] Request failed with status code 400
2024-06-24 12:56:28.883 ERROR (MainThread) [homeassistant.components.script.ollama_vision_front_door_camera_duplicate] Ollama Vision - Front Door Camera (Duplicate): Error executing script. Error for call_service at pos 2: Request failed with status code 400
2024-06-24 12:56:28.885 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140070967810304] Request failed with status code 400](url)`

**Comment by hsman2** [comment]
Quick update. It looks like it's just the camera entities coming from frigate. The camera entities from Home Assistant (like the reolink integration) work. But the ones provided by the frigate integration are giving me that error. And if it helps I'm running the new Frigate beta Addon (14.0 beta 3) but still using the latest version of the frigate integration (5.2). So maybe something in the new Frigate beta broke it? I know he did do a massive update from Frigate 13. So for now I'll just use the Camera entities provided by my reolink integration till a fix can be made.

**Comment by valentinfrlch** [comment]
Can you check in _developer tools_ under _states_ if those camera entities have an attribute called `entity_picture`?
It should look something like
```
/api/camera_proxy/camera.entity_name?token=some_token
```
gpt4vision takes the image from there, if the attribute doesn't exist (or the enpoint there) is not valid, this is likely the problem.


And if that endpoint is listed there, can you also check if you can access the image? In your browser go to
```
http://your-homeassistant-url:8123/api/camera_proxy/camera.entity_name?token=some_token
```
Can you see the image?

**Comment by hsman2** [comment]
Yes I've been on 0.4.3, even tried removing the integration, rebooting and resetting it back up and still getting the same error message.

**Comment by hsman2** [comment]
This is all that shows up in my Ollama logs, the ip 172.16.16.35 is my Home Assistant ip. 
```
time=2024-06-25T20:13:55.877Z level=WARN source=types.go:430 msg="invalid option provided" option=""
[GIN] 2024/06/25 - 20:13:56 | 400 |  130.044154ms |    172.16.16.35 | POST     "/api/chat"
```

**Comment by valentinfrlch** [comment]
Can you try the request with the `max_tokens `and `temperature` parameters set?
From the logs it looks like at least one of these was an empty string ("").

**Comment by hsman2** [comment]
Yeah both of them were already set to default values. I changed both of them a little and tried again. Still the same error. I'm guessing it's just my setup? I just don't understand why the camera entities provided via Reolink integration work fine but the ones provided via Frigate don't. Just makes no sense, I'll try just uninstalling the whole vision integration and redownloading it from strach. Maybe some file didn't get upgraded or something?

**Comment by valentinfrlch** [comment]
You're right both parameters are required. I've found this https://github.com/rjmacarthy/twinny/issues/251 issue which I think is related (even though this isn't the official ollama) Doesn't seem like they've found any solutions to this, but maybe something comes up. 

If you find anything please share it here, I'd love to fix this but really don't know where the problem lies.
