### ISSUE TITLE
Any way to format the response differently?

### ISSUE THREAD

**Issue by Someguitarist** [valentinfrlch/ha-gpt4vision#36]
Hello!  First, let me say thanks for this extension it's totally amazing.  My only request is if there's a way to get a 'clean' response back without the "response test: ' ' " part?

For my use case I've got it built in Assist to be able to ask 'Do you see an {object} in the {location}?'  So I can ask 'Do you see a dog in the back yard?' but the response it gives is "{'response_text': ' No, there is no dog visible in the image. The picture shows a backyard with a deck and a swing set. '}"

Is there an easy way to get just the text without the rest of it?  

Thanks!  I've been trying to edit it in the YAML, but I'm a dummy!

**Comment by valentinfrlch** [comment]
The 'clean' text is stored in `response.response_text`. What does your setup look like? Can you attach your YAML?

**Comment by Someguitarist** [comment]
Thanks for your help!  If I call response.response_text I just get 'Done' rather than the results.  I'm using one automation with multiple spec ID's for each different sentence.  Here's the YAML for the action for the search:

      - conditions:
          - condition: trigger
            id:
              - Search
        sequence:
          - service: gpt4vision.image_analyzer
            data:
              provider: Ollama
              model: llava
              include_filename: false
              target_width: 1280
              detail: high
              max_tokens: 100
              temperature: 0.5
              image_entity:
                - camera.backyard
              message: Do you see a {{ trigger.slots.thing }}
            response_variable: results
          - set_conversation_response: "{{ results }}"
            enabled: true

If I do it this way, I get what I mentioned about, the {'response_text} 'Yes there's a tree in the yard'}'

If I set the conversation response to response.response_text it just says 'Done' no matter what I do.

If I remove the last two lines so there's no conversation response it also just says 'Done'.

(Also, sidenote, I see the include filename tag for my other feature request!  I'll play with that in a minute too!  Thanks again for your help!)

**Comment by valentinfrlch** [comment]
It's strange that it returns 'Done' as it does seem to work otherwise.

I don't really have much experience with Assist as I use [Extended OpenAI Conversation](https://github.com/jekalmin/extended_openai_conversation). It is more customizable than the built-in agent, but can still be used through the Assist interface. It also allows for dynamic entity selection by the LLM so you don't need to write multiple automations.
I mention this because I use this myself and have written so-called 'specs' which is how you can write your own extensions to work with Extended OpenAI Conversation.
So while I unfortunately don't know how to fix Assist, I highly encourage you to try out Extended OpenAI Conversation.
You can find the specs I mentioned in the [wiki](https://github.com/valentinfrlch/ha-gpt4vision/wiki/Specs-for-Extended-OpenAI-Conversation).

**Comment by Someguitarist** [comment]
I've used Extended OpenAI before, but I currently use Home-LLM (https://github.com/acon96/home-llm) as it allows for a local LLM to have control over entities without relying on ChatGPT.  When I say 'Assist', I really mean the home-llm.  I'll have a look at that wiki and see if I can come up with any kind of work around.  

Ideally it's be nice to have a checkbox to change to a simpler output without the response.txt part.  But I *think* I can probably get that clean response if I figure out some YAML formatting.

That spec thing is really cool though!  That sounds like basically exactly what I'm trying to do, but I don't think I'd switch to Extended and give up LocalLLM control for it, at the moment.

**Comment by Someguitarist** [comment]
Figured it out!  You can mark this as closed.

For any other dummies like me, the correct last line should read:

{{ results.response_text }}

Now I get results and stuff like you were mentioning in the Wiki locally!  Whoo!  Yes, thanks!

**Comment by valentinfrlch** [comment]
Very glad to hear it's working now!
