### ISSUE TITLE
Add Ollama vision support

### ISSUE THREAD

**Issue by jmadden91** [valentinfrlch/ha-gpt4vision#4]
Thanks for your work with this integration. Works perfectly with openai. 

Would it be possible to add ollama as a supported provider? I tried adding it using the "localAI" provider with the port changed to 11434 and while it adds fine, I get a 400 error when trying to run the service.

Here is the ollama blog post about vision support:
[https://ollama.com/blog/vision-models](url)

![image](https://github.com/valentinfrlch/ha-gpt4vision/assets/30562276/5fa4db39-9241-4bd1-8ba5-77e9dc1dcb92)

Cheers!

**Comment by valentinfrlch** [comment]
Thank you for the suggestion,
I think ollama would be a great addition. The reason it doesn't work with localai is because the use different endpoints in their api.
However, this should be entirely doable. I think I can ship this in the next release.

**Comment by valentinfrlch** [comment]
Ollama is now supported as of v0.3.5

**Comment by mudler** [comment]
> Thank you for the suggestion,
> I think ollama would be a great addition. The reason it doesn't work with localai is because the use different endpoints in their api.
> However, this should be entirely doable. I think I can ship this in the next release.

Is there something I can help with? LocalAI should be entirely compatible with vision API, and we test that against our CI

**Comment by jmadden91** [comment]
> Ollama is now supported as of v0.3.5

Amazing, thank you so much. Works perfectly
