### ISSUE TITLE
Add “High, Low and Auto” Detail Parameter

### ISSUE THREAD

**Issue by WouterJN** [valentinfrlch/ha-gpt4vision#9]
It appears that controlling the detail parameter, which offers three options—low, high, or auto—is not currently possible. 

Being able to manage this parameter would be beneficial, as it would allow us to force GPT to either low or high fidelity. Selecting low fidelity reduces the cost to just 85 tokens per image. This enables the API to return responses more quickly and consume fewer input tokens, which is advantageous for use cases that do not require high detail.

Please also see: https://platform.openai.com/docs/guides/vision

**Comment by valentinfrlch** [comment]
Nice catch, I didn't know that option existed. Probably better than the current downscaling option. Will still leave the downscaler in there as I am unsure if the other providers (LocalAI and Ollama) support the detail parameter.
Working on this now.

**Comment by valentinfrlch** [comment]
The `detail` parameter has been implemented. For now it only has an effect for OpenAI as I don't have a LocalAI instance running to test. (Ollama's API docs don't mention the parameter).
It will be included in the next release 🚀

**Comment by WouterJN** [comment]
Thank you! I agree with keeping the downscaling option, as it helps save upload time for large images and is useful when using other models. Could you also adjust the minimum width for the downscale option to 512 pixels?

**Comment by valentinfrlch** [comment]
Sure! I’ll push it tomorrow
